/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ceiling_fan.glb 
Author: Graham Rust (https://sketchfab.com/GRXR.ca)
License: COPYRIGHT TO Graham Rust
Source: https://sketchfab.com/3d-models/ceiling-fan-9f91a04f7e8242179ba201b16bc4bd2e
Title: Ceiling Fan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ceiling_fan.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} position={[-233.136, 94.5, -24.269]} rotation={[-Math.PI / 2, 0, 0]} scale={0.394} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ceiling_fan.glb')
