import PanelAirConditioners from "./PanelAirConditioners"
export const metadata = {
  title: "Top Panel AC Manufacturer - Authorized Govt. Supplier | Adhunik Powertech",
  description: "Protect your electrical panels from overheating with heavy-duty Panel Air Conditioners by Adhunik Powertech. Reliable enclosure cooling for CNC machines & industrial control cabinets. Get a free quote today.",
  keywords: [
    "Panel AC",
    "Panel Air Conditioner",
    "Industrial Panel AC",
    "Government Supplier Panel AC",
    "Authorized Panel AC Supplier",
    "Top Panel AC Manufacturer",
    "Heavy Duty Panel AC",
    "Low Maintenance Panel AC",
    "Durable Panel AC",
    "Adhunik Powertech Panel AC",
    "panel ac price",
    "panel ac for electrical panel",
    "advance cooling-panel ac",
    "Panel air conditioner on gem",
    "panel air conditioner price",
    "Industrial Panel Air Conditioner",
    "Electrical Cabinet Cooling System",
    "Panel AC for Pharmaceutical",
    "Panel AC for Food Processing",
    "Panel AC for Engineering",
    "Panel AC for Manufacturing",
    "CNC Panel Cooling",
    "VFD Panel Cooling",
    "Server Cabinet Cooling",
    "Industrial Automation Cooling",
    "Manufacturing Floor Cooling",
    "Data Center Cooling",
    "Telecommunication Shelter Cooling",
    "Sealed Enclosure Cooling",
    "Ahmedabad Panel AC",
    "Pune Panel AC",
    "Hyderabad Panel AC",
    "Chennai Panel AC",
    "Mumbai Panel AC",
    "Goa Panel AC",
    "Vishakhapatnam Panel AC",
    "Bhopal Panel AC",
    "Kolkata Panel AC",
    "Jaipur Panel AC",
    "Delhi Panel AC",
    "Gujarat Industrial Cooling",
    "Rajasthan Industrial Cooling",
    "Chhattisgarh Industrial Cooling",
    "Odisha Industrial Cooling",
    "Panel air conditioner for CNC machines",
    "Panel air conditioner for VFD drives",
    "Best panel air conditioner for industrial use",
    "Reliable electrical panel cooling solutions",
    "Authorized panel air conditioner supplier",
    "Panel AC maintenance and support",
    "Industrial enclosure cooling systems",
    "Thermal management for PLC cabinets",
    "Panel air conditioner for manufacturing plants",
    "Panel air conditioner for food processing units",
    "Panel air conditioner for pharmaceutical industry",
    "Panel air conditioner for data centers",
    "Panel air conditioner for telecommunication shelters",
    "Panel air conditioner for server rooms",
    "Panel air conditioner for industrial automation",
    "Panel air conditioner for electrical control panels",
    "Panel air conditioner for industrial machinery",
    "Panel air conditioner for CNC machines and VFD drives",
    "Panel air conditioner for manufacturing and production facilities",
    "Panel air conditioner for industrial equipment and machinery",
    "Panel air conditioner for industrial control systems",
    "Panel air conditioner for industrial automation and robotics",
    "Panel air conditioner for industrial process control",
    "Panel air conditioner for industrial electrical enclosures",
    "Panel air conditioner for industrial control cabinets and panels",
    "Panel air conditioner for industrial electrical control systems and machinery",
    "Panel air conditioner for industrial automation and process control systems",
    "Panel air conditioner for industrial electrical enclosures and control cabinets",
    "Panel air conditioner for industrial control panels and machinery",
    "Panel air conditioner for industrial automation and robotics systems",
    "Panel air conditioner manufactuer in India",
    "Panel air conditioner supplier in India",
    "Panel air conditioner exporter in India",
    "Panel air conditioner dealer in India",
    "Panel air conditioner distributor in India",
    "Panel air conditioner wholesaler in India",
    "Panel air conditioner retailer in India",
    "Panel air conditioner service provider in India",
    "Panel air conditioner maintenance provider in India",
    "Panel air conditioner installation provider in India",
    "Panel air conditioner repair provider in India",
    "Panel air conditioner support provider in India",
    "Panel air conditioner solutions provider in India",
    "Panel air conditioner manufacturer and supplier in India",
    "Panel air conditioner manufacturer and exporter in India",
    "Panel air conditioner manufacturer and dealer in India",
    "Panel air conditioner manufacturer and distributor in India",
    "Panel air conditioner manufacturer and wholesaler in India",
    "Panel air conditioner manufacturer and retailer in India",
    "Panel air conditioner manufacturer and service provider in India",
    "Panel air conditioner manufacturer and maintenance provider in India",
    "Panel air conditioner manufacturer and installation provider in India",
    "Panel air conditioner manufacturer and repair provider in India",
    "Panel air conditioner manufacturer and support provider in India",
    "Panel air conditioner manufacturer and solutions provider in India",
    "Panel ac manufacturer and supplier for industrial applications in India",
    "Panel ac manufacturer and supplier for electrical enclosures in India",
    "Panel ac manufacturer and supplier for CNC machines in India",
    "Panel ac manufacturer and supplier for VFD drives in India",
    "Panel ac manufacturer and supplier for manufacturing plants in India",
    "Panel ac manufacturer and supplier for food processing units in India",
    "Panel ac manufacturer and supplier for pharmaceutical industry in India",
    "Panel ac manufacturer and supplier for data centers in India",
    "Panel ac manufacturer and supplier for telecommunication shelters in India",
    "Panel ac manufacturer and supplier for server rooms in India",
    "Panel ac manufacturer and supplier for industrial automation in India",
    "Panel ac manufacturer and supplier for electrical control panels in India",
    "Panel ac manufacturer and supplier for industrial machinery in India",
    "Panel ac manufacturer and supplier for industrial control systems in India",
    "Panel ac manufacturer and supplier for industrial automation and robotics in India",
    "Panel ac manufacturer and supplier for industrial process control in India",
    "Panel ac manufacturer and supplier for industrial electrical enclosures in India",
    "Panel ac manufacturer and supplier for industrial control cabinets and panels in India",
    "Panel ac manufacturer and supplier for industrial electrical control systems and machinery in India",
    "Panel ac manufacturer and supplier for industrial automation and process control systems in India",
    "Panel ac manufacturer and supplier for industrial electrical enclosures and control cabinets in India",
    "Panel ac manufacturer and supplier for industrial control panels and machinery in India",
    "Panel ac manufacturer and supplier for industrial automation and robotics systems in India",
    "Panel ac manufacturer and supplier for industrial applications and machinery in India",
    "Panel ac manufacturer and supplier for industrial applications and control systems in India",
    "Panel ac manufacturer and supplier for industrial applications and automation in India",
    "Top panel ac manufacturer in India",
    "Authorized panel ac supplier in India",
    "Government approved panel ac manufacturer in India",
    "Government approved panel ac supplier in India",
    "Reliable panel ac manufacturer in India",
    "Durable panel ac supplier in India",
    "Heavy duty panel ac manufacturer in India",
    "Low maintenance panel ac supplier in India",
    "Industrial panel ac manufacturer in India",
    "Industrial panel ac supplier in India",
    "Panel ac manufacturer for electrical panels in India",
    "Panel ac supplier for electrical panels in India",
    "Panel ac manufacturer for industrial applications in India",
    "Panel ac supplier for industrial applications in India",
    "Panel ac manufacturer for CNC machines in India",
    "Panel ac supplier for CNC machines in India",
    "Panel ac manufacturer for VFD drives in India",
    "Panel ac supplier for VFD drives in India",
    "Panel ac manufacturer for manufacturing plants in India",
    "Panel ac supplier for manufacturing plants in India",
    "Panel ac manufacturer for food processing units in India",
    "Panel ac supplier for food processing units in India",
    "Panel ac manufacturer for pharmaceutical industry in India",
    "Panel ac supplier for pharmaceutical industry in India",
    "Panel ac manufacturer for data centers in India",
    "Panel ac supplier for data centers in India",
    "Panel ac manufacturer for telecommunication shelters in India",
    "Panel ac supplier for telecommunication shelters in India",
    "Panel ac manufacturer for server rooms in India",
    "Panel ac supplier for server rooms in India",
    "Panel ac manufacturer for industrial automation in India",
    "Enclosure cooling solutions provider in India",
    "Electrical panel cooling solutions provider in India",
    "Industrial panel cooling solutions provider in India", 
    "Enclosure cooling systems manufacturer in India",
    "Electrical panel cooling systems manufacturer in India",
    "Industrial panel cooling systems manufacturer in India",
    "Enclosure cooling systems supplier in India",
    "Electrical panel cooling systems supplier in India",
    "Industrial panel cooling systems supplier in India",
    "Best panel ac manufacturer in India",
    "Best panel ac supplier in India",
    "Top rated panel ac manufacturer in India",
    "Top rated panel ac supplier in India",
    "Leading panel ac manufacturer in India",
    "Leading panel ac supplier in India",
    "Trusted panel ac manufacturer in India",
    "Trusted panel ac supplier in India",
    "adhunik powertech panel ac manufacturer in India",
    "adhunik powertech panel ac supplier in India",
    "affordable panel ac manufacturer in India",
    "affordable panel ac supplier in India",
    "high quality panel ac manufacturer in India",
    "high quality panel ac supplier in India",
    "custom panel ac manufacturer in India",
    "custom panel ac supplier in India",
    "industrial panel ac manufacturer in India",  
    "industrial panel ac supplier in India",
    "panel ac manufacturer for industrial applications in India",
    "panel ac supplier for industrial applications in India",
    "panel ac manufacturer for electrical panels in India", 
    "panel ac supplier for electrical panels in India",
    "panel ac manufacturer for CNC machines in India",
    "panel ac supplier for CNC machines in India",
    "advanced panel ac manufacturer in India",
    "advanced panel ac supplier in India",
    "innovative panel ac manufacturer in India",
    "innovative panel ac supplier in India",
    "rital panel ac manufacturer in India",
    "rital panel ac supplier in India",
    "emerson panel ac manufacturer in India",
    "emerson panel ac supplier in India",
    "liebert panel ac manufacturer in India",
    "liebert panel ac supplier in India", 
    "panel ac manufacturer for industrial control cabinets in India",
    "panel ac supplier for industrial control cabinets in India",
    "panel ac manufacturer for electrical enclosures in India",
    "panel ac supplier for electrical enclosures in India",
    "hexacool panel ac manufacturer in India",
    "hexacool panel ac supplier in India",
    "panel ac manufacturer for industrial machinery in India",
    "panel ac supplier for industrial machinery in India", 
    "panel ac manufacturer for industrial control systems in India",
    "panel ac supplier for industrial control systems in India",
    "panel ac manufacturer for industrial automation and robotics in India",
    "tempcool panel ac manufacturer in India",
    "tempcool panel ac supplier in India",
    "panel ac manufacturer for industrial process control in India",
    "panel ac supplier for industrial process control in India",
    "panel ac manufacturer for industrial electrical enclosures in India",
    "panel ac supplier for industrial electrical enclosures in India",
    "panel ac manufacturer for industrial control cabinets and panels in India",
    "panel ac supplier for industrial control cabinets and panels in India",
    "panel ac manufacturer for industrial electrical control systems and machinery in India",
    "panel ac supplier for industrial electrical control systems and machinery in India",
    "panel ac manufacturer for industrial automation and process control systems in India",
    "panel ac supplier for industrial automation and process control systems in India",
    "panel ac manufacturer for industrial electrical enclosures and control cabinets in India",
    "panel ac supplier for industrial electrical enclosures and control cabinets in India",
    "panel ac manufacturer for industrial control panels and machinery in India",
    "panel ac supplier for industrial control panels and machinery in India",
    "panel ac manufacturer in Rajasthan, India",
    "panel ac supplier in Rajasthan, India",
    "panel ac manufacturer in Gujarat, India",
    "panel ac supplier in Gujarat, India",
    "panel ac manufacturer in Chhattisgarh, India",
    "panel ac supplier in Chhattisgarh, India",
    "panel ac manufacturer in Odisha, India",
    "panel ac supplier in Odisha, India",
    "panel ac manufacturer in Maharashtra, India",
    "panel ac supplier in Maharashtra, India",
    "panel ac manufacturer in Telangana, India",
    "panel ac supplier in Telangana, India",
    "panel ac manufacturer in Andhra Pradesh, India",
    "panel ac supplier in Andhra Pradesh, India",
    "panel ac manufacturer in Tamil Nadu, India",
    "panel ac supplier in Tamil Nadu, India",
    "panel ac manufacturer in Karnataka, India",
    "panel ac supplier in Karnataka, India",
    "panel ac manufacturer in West Bengal, India",
    "panel ac supplier in West Bengal, India",
    "panel ac manufacturer in Madhya Pradesh, India",
    "panel ac supplier in Madhya Pradesh, India", 
    "panel ac manufacturer in Uttar Pradesh, India",
    "panel ac supplier in Uttar Pradesh, India",
    "panel ac manufacturer in Bihar, India",
    "panel ac supplier in Bihar, India",
    "panel ac manufacturer in Jharkhand, India",
    "panel ac supplier in Jharkhand, India",  
    "panel ac manufacturer in Assam, India",
    "panel ac supplier in Assam, India",
    "panel ac manufacturer in Punjab, India",
    "panel ac supplier in Punjab, India",
    "panel ac manufacturer in Haryana, India",
    "panel ac supplier in Haryana, India",
    "panel ac manufacturer in Himachal Pradesh, India",
    "panel ac supplier in Himachal Pradesh, India",
    "panel ac manufacturer in Uttarakhand, India",
    "panel ac supplier in Uttarakhand, India",
    "panel ac manufacturer in Delhi, India",
    "panel ac supplier in Delhi, India",
    "which is the best panel ac manufacturer in India",
    "which is the best panel ac supplier in India",
    "which is the most reliable panel ac manufacturer in India",
    "which is the most reliable panel ac supplier in India",
    "which is the most trusted panel ac manufacturer in India",
    "which is the most trusted panel ac supplier in India",
    "which is the most durable panel ac manufacturer in India",
    "which is the most durable panel ac supplier in India",
    "which is the most heavy duty panel ac manufacturer in India",
    "which is the most heavy duty panel ac supplier in India",  
    "which is the most low maintenance panel ac manufacturer in India",
    "which is the most low maintenance panel ac supplier in India",
    "which is the most advanced panel ac manufacturer in India",
    "which is the most advanced panel ac supplier in India",
    "which is the most innovative panel ac manufacturer in India",
    "which is the most innovative panel ac supplier in India",
    "which is the most affordable panel ac manufacturer in India",
    "which is the most affordable panel ac supplier in India",
    "which is the most high quality panel ac manufacturer in India",
    "which is the most high quality panel ac supplier in India",
    "which is the most custom panel ac manufacturer in India",
    "which is the most custom panel ac supplier in India",
    "which is the most industrial panel ac manufacturer in India",
    "which is the most industrial panel ac supplier in India",
    "which is the most authorized panel ac manufacturer in India",
    "which is the most authorized panel ac supplier in India",
    "which is the most government approved panel ac manufacturer in India",
    "which is the most government approved panel ac supplier in India",
    "which is the most reliable panel ac manufacturer in India",
    "which is the most reliable panel ac supplier in India",
    "which is the most durable panel ac manufacturer in India",
    "which is the most durable panel ac supplier in India",
  ],
  
  robots: "index, follow",
  openGraph: {
    title: "Top Panel AC Manufacturer - Authorized Govt. Supplier | Adhunik Powertech",
    description: "Protect your electrical panels from overheating with heavy-duty Panel Air Conditioners by Adhunik Powertech. Reliable enclosure cooling for CNC machines & industrial control cabinets. Get a free quote today.",
    url: "https://www.adhunikpowertech.com/panel-air-conditioners",
    type: "article",
    images: [
      {
        url: "https://www.adhunikpowertech.com/_next/image?url=%2Fpanelac.png&w=640&q=75",
        width: 800,
        height: 600,
        alt: "Adhunik Powertech Panel AC Units",
      },
    ],
  },
  alternates: {
    canonical: "https://www.adhunikpowertech.com/panel-air-conditioners",
  },
  twitter: {
    card: "summary_large_image",
    title: "Panel Air Conditioner Manufacturer in India | Adhunik Powertech",
    description: "Protect your electrical panels from overheating with heavy-duty Panel Air Conditioners by Adhunik Powertech. Reliable enclosure cooling for CNC machines & industrial control cabinets. Get a free quote today.",
    image: "https://www.adhunikpowertech.com/_next/image?url=%2Fpanelac.png&w=640&q=75",
  },
};

export default function () {

  return (

    <>
      <PanelAirConditioners />
    </>
  )
}
