"use client"
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import {
  ShieldCheck,
  GaugeCircle,
  Thermometer,
  Clock,
  BadgeDollarSign,
  Hammer,
  Boxes,
  FileCheck2,
  Ruler,
  AlertTriangle,
  Trash2
} from "lucide-react";

import {
  ScanSearch,
  Users2,
  ThermometerSun,
  Wrench,
  SlidersHorizontal,
  BarChart3,

  Wind,
  LayoutTemplate,
  Plug,
  Cpu
} from "lucide-react";

import {
  CalendarCheck2,
  Radar,
  Repeat2,
  LineChart,
  ThumbsDown,
  ShieldX,
  ClipboardCheck,
  Building2
} from "lucide-react";

import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";


import { PhoneCall, AlarmClockCheck, MapPin, PackageCheck } from 'lucide-react';
import { RefreshCw, } from 'lucide-react';


export default function ElectricalCabinets() {

  const [openIndex, setOpenIndex] = useState(null);

  const toggle = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const energySystems = [

    {
      title: 'Filter Fans',
      desc: <>

        <p>
        <strong className=' text-cyan-600 font-semibold'>How They Work : </strong>  
        Filter fans use a simple "open-loop" system, drawing cooler, filtered air from the outside and pushing hot air out.
</p>

        <p>
        <strong className=' text-cyan-600 font-semibold'> Best For : </strong>  
      Relatively clean Environments, with a stable, cooler ambient temperature than the desired internal temperature. This is a cost-effective solution for light heat loads.

</p>


        <p>
        <strong className=' text-cyan-600 font-semibold'> Limitation : </strong>  
    Fans cannot cool the cabinet below the ambient air temperature and can introduce dust and humidity into the enclosure if not properly maintained.

</p>


      </>,
      icon: 'M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4'
    },

  
    {
      title: 'Air-to-Air Heat Exchangers',
      desc: <>

        <p>
        <strong className=' text-cyan-600 font-semibold'> How They Work : </strong>  
       These systems use a "closed-loop" design. They have two separate air circuits—one for inside the cabinet and one for the outside. Heat is transferred from the internal air to the external air without the two air streams ever mixing.

</p>

        <p>
        <strong className=' text-cyan-600 font-semibold'> Best For : </strong>  
    Sealed cabinets in environments with high levels of dust, dirt, or moisture. They prevent contaminants from entering the enclosure while still providing effective cooling.

</p>

    <p>
        <strong className=' text-cyan-600 font-semibold'> Limitation : </strong>  
    Similar to fans, heat exchangers cannot cool the cabinet below the ambient temperature.

</p>

      </>,
      icon: 'M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4'
    },

  
    {
      title: 'Panel Air Conditioners (The Ultimate Solution)',
      desc: <>

        <p>
        <strong className=' text-cyan-600 font-semibold'> How They Work : </strong>  
    Panel air conditioners are the most robust "closed-loop" cooling solution. They use a compressor-based refrigeration cycle (just like your home AC) to remove heat from the cabinet actively.
</p>


        <p>
        <strong className=' text-cyan-600 font-semibold'> Best For : </strong>  
   Applications with high heat loads, or when the ambient temperature is higher than the required internal temperature. They are essential for protecting high-value components and ensuring continuous operation in harsh environments.
</p>


    <p>
        <strong className=' text-cyan-600 font-semibold'>  Benefit : </strong>  
   A panel air conditioner not only cools but also dehumidifies the air inside the cabinet, protecting electronics from moisture and condensation, and can be used to achieve precise temperature control.

</p>

      </>,
      icon: 'M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4'
    },

  
  ];


  const ClientReferences = [
    {
      description: <>
        <p> <strong className=' font-semibold  text-cyan-700'>Calculate the Heat Load :</strong>  This is the most crucial step. You must sum the heat generated by every component inside the cabinet (in Watts or BTUs). Manufacturers' datasheets or online calculators can help you with this.
</p>
      </> ,
    },

   
    {
      description: <>
        <p> <strong className=' font-semibold  text-cyan-700'>Consider the Environment :</strong>  Assess the maximum ambient temperature, the presence of dust or moisture, and whether the cabinet is exposed to direct sunlight.

</p>
      </> ,
    },

   
    {
      description: <>
        <p> <strong className=' font-semibold  text-cyan-700'>Choose the Right Mounting : </strong>  Panel air conditioners come in various mounting styles—wall-mount, top-mount, and standalone—to fit your specific cabinet layout.


</p>
      </> ,
    },

   
  ];

  const warrantyTypes = [
    {
      title: "Manufacturer Equipment Warranties",
      description:
        "These cover the major components (compressors, heat exchangers, motors) and often vary in length (e.g., 5, 10, or even 15 years) and coverage based on the specific equipment. Some manufacturers offer extended warranties or performance guarantees for critical components.",
    },
    {
      title: "Contractor Workmanship Warranties",
      description:
        "These cover the labor and installation quality provided by the contractor. The duration can range from 1 to 5 years, but for complex commercial installations, aim for a longer period. This warranty is vital as proper installation is key to system longevity and efficiency.",
    },
    {
      title: "Parts Replacement Warranties",
      description:
        "Beyond major components, inquire about warranties for smaller, frequently replaced parts that can impact uptime.",
    },
  ];

  const warrantyDocumentation = [
    {
      title: "Coverage Scope",
      description:
        "Clearly delineate what is covered (parts, labor, specific components) and what is excluded (e.g., routine maintenance, acts of God, damage from improper operation by facility staff).",
    },
    {
      title: "Duration",
      description:
        "Note the start and end dates for all warranty types.",
    },
    {
      title: "Transferability",
      description:
        "If you plan to sell the property, can the warranty be transferred to the new owner?",
    },
    {
      title: "Claim Process",
      description:
        "Understand the exact procedure for making a warranty claim, including required documentation, response times, and authorized service providers.",
    },
    {
      title: "Maintenance Requirements",
      description:
        "Many warranties are contingent on adhering to a strict schedule of preventative maintenance performed by qualified technicians. Failure to do so can void your warranty.",
    },
  ];


  const KeyTakeaways = [
    {
        title:"Internal Heat Load",
      description: "Always verify the HVAC contractor possesses the necessary commercial/industrial licenses, certifications, and comprehensive insurance.",
    },
   
    {
        title:"High Ambient Temperatures",
      description: "If your factory or work environment is hot, the heat from the surrounding air is transferred into the cabinet, adding to the internal heat load.",
    },
   
    {
        title:"Sealed Enclosures",
      description: "While crucial for protection, sealed enclosures (e.g., NEMA 4X or IP66) prevent natural heat dissipation, trapping hot air inside.",
    },
   
    {
        title:"Blocked Airflow",
      description: "Poor cable management, obstructed vents, or clogged filters can restrict airflow, creating hot spots that can damage components even if the overall cabinet temperature seems acceptable.",

    },
   


  ];

  const Understanding = [
    {
      title: "ASHRAE 90.1",
      description: "A widely adopted standard for energy efficiency in commercial buildings.",
    },

    {
      title: " Local and State Energy Codes",
      description: " Specific regulations that dictate minimum efficiency requirements for new installations and retrofits.",
    },
    {
      title: "Utility Rebate Programs",
      description: "Opportunities for your business to receive financial incentives for installing high-efficiency equipment."
    },
    {
      title: "Carbon Emission Reduction Targets",
      description: "For businesses committed to sustainability, the contractor should understand how to contribute to these goals."
    }

  ];

  const performanceGuarantees = [
    {
      title: "Energy Consumption Guarantees",
      description:
        "A promise that the new system will achieve a certain level of energy savings or consumption, with penalties if not met.",
      icon: GaugeCircle,
    },
    {
      title: "Temperature or Humidity Guarantees",
      description:
        "Ensuring the system can maintain specified environmental conditions within your facility.",
      icon: Thermometer,
    },
    {
      title: "Uptime Guarantees",
      description:
        "Particularly for mission-critical systems, a contractor might guarantee a certain percentage of operational uptime, with compensation for failures.",
      icon: Clock,
    },
  ];

  const pricingBreakdown = [
    {
      title: "Equipment Costs",
      description:
        "Itemized list of all major components (chillers, boilers, air handling units, controls, etc.) and their specific models/specifications.",
      icon: Boxes,
    },
    {
      title: "Labor Costs",
      description:
        "Broken down by type of labor (e.g., skilled technicians, sheet metal workers, electricians) and estimated hours.",
      icon: Hammer,
    },
    {
      title: "Materials and Consumables",
      description:
        "Detailed list of piping, insulation, ductwork, wiring, refrigerants, etc.",
      icon: Ruler,
    },
    {
      title: "Permit Fees and Inspection Costs",
      description: "All necessary regulatory fees.",
      icon: FileCheck2,
    },
    {
      title: "Engineering and Design Fees",
      description:
        "For complex installations, this might include detailed load calculations, system design, and blueprint creation.",
      icon: ShieldCheck,
    },
    {
      title: "Contingency Fees",
      description:
        "A reasonable contingency (e.g., 5-10%) for unforeseen issues, clearly outlined.",
      icon: AlertTriangle,
    },
    {
      title: "Disposal/Recycling Costs",
      description: "For old equipment, especially refrigerants.",
      icon: Trash2,
    },
  ];


  const servicePackages = [
    {
      title: "Preventative Maintenance Contracts",
      description:
        " Essential for maximizing system lifespan and efficiency. These should include regular inspections, cleaning, filter changes, lubrication, and system diagnostics. They may offer tiered levels (e.g., quarterly, semi-annual, annual)",
      icon: CalendarCheck2,
    },
    {
      title: "Emergency Service Contracts",
      description:
        "Crucial for minimizing downtime. Ask about guaranteed response times (e.g., within 2-4 hours for critical failures), 24/7 availability, and whether emergency labor rates are included or discounted.",
      icon: AlertTriangle,
    },
    {
      title: "Predictive Maintenance (PdM) / Condition-Based Monitoring",
      description:
        "Utilizing sensors and data analytics to anticipate failures before they occur, allowing for proactive maintenance and reducing unplanned downtime. This is particularly valuable for mission-critical systems.",
      icon: Radar,
    },
    {
      title: "Retro-Commissioning Services",
      description:
        "Optimizing existing systems to improve performance and energy efficiency without major equipment replacement.",
      icon: Repeat2,
    },
    {
      title: "HVAC System Audits and Optimization Plans",
      description:
        "Regular assessments to identify opportunities for efficiency improvements and cost reductions.",
      icon: LineChart,
    },
  ];

  const redFlags = [
    {
      title: "Substandard Equipment",
      description:
        "Use of cheaper, less efficient, or lower durability components.",
      icon: ThumbsDown,
    },
    {
      title: "Inadequate Labor",
      description:
        "Employing less experienced technicians or insufficient staffing for the project timeline.",
      icon: Hammer,
    },
    {
      title: "Missing Scope",
      description:
        "Omitting crucial aspects of the project (e.g., permits, complex ductwork, specialized controls) that will later be added as costly change orders.",
      icon: ClipboardCheck,
    },
    {
      title: "Lack of Insurance/Bonding",
      description:
        "Operating without adequate protection for your business.",
      icon: ShieldX,
    },
  ];

  const evaluationChecklist = [
    {
      title: "Assess Building Envelope",
      description:
        "Analyze insulation R-values, window types, roof construction, and potential air infiltration points.",
      icon: ScanSearch,
    },
    {
      title: "Understand Occupancy and Usage",
      description:
        "Determine varying occupancy loads, operational hours, and specific temperature/humidity requirements for different zones (e.g., offices, manufacturing floors, server rooms, cold storage).",
      icon: Users2,
    },
    {
      title: "Evaluate Internal Heat Loads",
      description:
        "Account for heat generated by machinery, lighting, computers, and processes, which can be substantial in commercial and industrial settings.",
      icon: ThermometerSun,
    },
    {
      title: "Inspect Existing HVAC Infrastructure",
      description:
        "Thoroughly examine current equipment, ductwork (for leaks, blockages, proper sizing), piping, controls, and electrical infrastructure.",
      icon: Wrench,
    },
    {
      title: "Review Process Requirements",
      description:
        "For industrial facilities, understand specific process cooling, ventilation, dust collection, or air purification needs.",
      icon: SlidersHorizontal,
    },
    {
      title: "Discuss Business Objectives",
      description:
        "Engage with facility managers and business leaders to understand critical uptime needs, energy efficiency goals, budget constraints, and future expansion plans.",
      icon: BarChart3,
    },
    {
      title: "Analyze Historical Energy Data",
      description:
        "Request past utility bills to identify consumption patterns and potential areas for savings.",
      icon: Ruler,
    },
  ];

  const designChecklist = [
    {
      title: "Undersized Systems",
      description:
        "Will struggle to maintain desired temperatures, leading to occupant discomfort, equipment overheating, and excessive energy consumption as they run continuously.",
      icon: Wind,
    },
    {
      title: "Oversized Systems",
      description:
        "Will short-cycle frequently, leading to poor humidity control, uneven temperatures, premature wear and tear on components, and wasted energy.",
      icon: LayoutTemplate,
    },
    {
      title: "Detailed Load Calculations",
      description:
        "Using industry-standard methodologies (e.g., ASHRAE Manual J or T for commercial applications, or specialized industrial calculations) to precisely determine the required capacity for your specific facility.They should consider latent and sensible heat loads, ventilation requirements, and process demands. This leads to a custom-designed system that operates efficiently and reliably.",
      icon: Ruler,
    },
  ];

  const systemAssessment = [
    {
      title: "Ductwork Integrity and Design",
      description:
        "Look for leaks, obstructions, proper sizing for airflow, insulation levels, and zoning capabilities. Inadequate ductwork can severely compromise even the most efficient HVAC unit.",
      icon: Wind,
    },
    {
      title: "Piping Systems",
      description:
        "For hydronic systems (chillers, boilers), inspect pipe sizing, insulation, valve functionality, and pump efficiency.",
      icon: Plug,
    },
    {
      title: "Building Automation System (BAS) Integration",
      description:
        "How will the new HVAC system integrate with existing building controls? A well-integrated system offers superior control, monitoring, and energy management.",
      icon: Cpu,
    },
    {
      title: "Electrical and Structural Considerations",
      description:
        "Ensure your facility's electrical supply can handle new equipment and that structural elements can support new installations.",
      icon: Building2,
    },
  ];

  const benefits = [
    {
      icon: <ShieldCheck className="text-cyan-600 w-12 h-12" />,
      title: "Maximized Uptime",
      description:
        "Reduces the likelihood of unexpected breakdowns, which can halt production, damage sensitive equipment, or compromise environmental conditions."
    },
    {
      icon: <RefreshCw className="text-cyan-600 w-12 h-12" />,
      title: "Optimized Energy Efficiency",
      description:
        "Regular tune-ups, cleaning, and calibration ensure components operate at their intended efficiency, leading to significant energy cost savings."
    },
    {
      icon: <Clock className="text-cyan-600 w-12 h-12" />,
      title: "Extended Equipment Lifespan",
      description:
        "Proactive identification and resolution of minor issues prevent them from escalating into major, costly repairs, thereby prolonging the life of expensive equipment."
    },
    {
      icon: <ShieldCheck className="text-cyan-600 w-12 h-12" />,
      title: "Compliance and Safety",
      description:
        "Ensures systems meet regulatory standards for indoor air quality, safety, and environmental impact."
    },
    {
      icon: <CalendarCheck2 className="text-cyan-600 w-12 h-12" />,
      title: "Preserved Warranties",
      description:
        "Most manufacturer warranties for commercial equipment mandate regular professional maintenance."
    }
  ];

  const maintenancePlans = [
    {
      title: "Basic Inspection/Tune-up Plans",
      description:
        "Annual or semi-annual checks, filter changes, coil cleaning, and basic operational checks."
    },
    {
      title: "Comprehensive PM Contracts",
      description:
        "Include all basic services plus more in-depth diagnostics, specific component checks, lubrication, belt replacements, and potential discounts on parts and labor for covered repairs."
    },
    {
      title: "Full-Service Contracts",
      description:
        "The most inclusive, often covering all parts and labor for repairs (excluding major equipment replacement), with prioritized service. This offers the highest level of budget predictability."
    },
    {
      title: "Predictive Maintenance (PdM) Plans",
      description:
        "Utilizing advanced technologies like vibration analysis, thermography, and oil analysis to monitor equipment health and predict failures, allowing for maintenance to be scheduled proactively before a breakdown occurs."
    },
    {
      title: "Seasonal Commissioning",
      description:
        "Optimizing systems specifically for heating or cooling seasons to ensure peak performance."
    }
  ];

  const supportItems = [
    {
      icon: <PhoneCall className="text-cyan-600 w-14 h-14" />,
      title: "24/7/365 Availability",
      description:
        "Do they offer round-the-clock emergency service, including holidays?"
    },
    {
      icon: <AlarmClockCheck className="text-cyan-600 w-14 h-14" />,
      title: "Guaranteed Response Times",
      description:
        "What is their promised response time for critical failures (e.g., within 2-4 hours)? Are these legally binding in the contract?"
    },
    {
      icon: <PhoneCall className="text-cyan-600 w-14 h-14" />,
      title: "Dedicated Emergency Line/Dispatch",
      description:
        "Do they have a clear, easy-to-access system for emergency calls?"
    },
    {
      icon: <MapPin className="text-cyan-600 w-14 h-14" />,
      title: "Geographic Coverage",
      description:
        "Ensure their emergency service extends to your facility's location."
    },
    {
      icon: <AlertTriangle className="text-cyan-600 w-14 h-14" />,
      title: "After-Hours Rates",
      description:
        "Understand any premium charges for emergency or after-hours service."
    },
    {
      icon: <PackageCheck className="text-cyan-600 w-14 h-14" />,
      title: "Parts Availability",
      description:
        "Do they stock common commercial/industrial parts or have rapid access to suppliers to minimize downtime?"
    }
  ];


  const faqItems = [
    {
      question:
        "Why is it important to hire a licensed HVAC contractor with commercial specialization?",
      answer:
        "Hiring a contractor with commercial-specific licenses ensures they possess the necessary expertise for complex systems, adhere to stringent building codes, and carry appropriate insurance, protecting your business from operational and legal risks."
    },
    {
      question:
        "How can I verify a commercial HVAC contractor's experience and reputation?",
      answer:
        "Request detailed client references from similar commercial projects, ask for case studies, and inquire about their safety record (e.g., EMR). While online reviews are helpful, direct commercial client feedback is more valuable."
    },
    {
      question:
        "Why are energy efficiency services crucial for commercial spaces?",
      answer:
        "Energy efficiency services for commercial HVAC systems can lead to significant reductions in operational costs, lower carbon emissions, and improved compliance with environmental regulations, directly impacting your business's profitability and sustainability."
    },
    {
      question:
        "What specific types of warranties and guarantees should I inquire about for commercial HVAC?",
      answer:
        "Ask about comprehensive manufacturer equipment warranties, detailed contractor workmanship warranties, and, most importantly, Service Level Agreements (SLAs) that outline guaranteed response times and potential performance guarantees for system uptime and energy consumption."
    },
    {
      question:
        "How do commercial maintenance plans benefit businesses?",
      answer:
        "Regular, tailored maintenance plans for commercial HVAC systems prevent costly breakdowns, extend equipment lifespan, optimize energy efficiency, ensure compliance, and provide budget predictability, minimizing operational disruptions and maximizing ROI."
    }
  ];

  const items = [
    {
      title: "Load Calculations",
      description:
        "Precise determination of heating and cooling loads based on building envelope, occupancy, equipment, and processes.",
    },
    {
      title: "Blower Door Tests (for smaller commercial spaces) / Thermal Imaging",
      description: "Identifying air leakage and insulation deficiencies.",
    },
    {
      title: "Ductwork Integrity Testing",
      description: "Assessing leaks and blockages in large-scale duct systems.",
    },
    {
      title: "System Performance Baselines",
      description: "Establishing current energy usage and identifying areas for improvement.",
    },
  ];
  return (
    <>

      <div className="bg-gradient-to-b mt-24  ">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">

          {/* Hero Section */}
          <section className="flex flex-col md:flex-row gap-8 items-center mb-16">
            <div className=" w-full md:w-6/12">

              <Image
                src="https://res.cloudinary.com/ddkyx2jhh/image/upload/v1756275050/electrical_cabinets_3_eftuxm.webp"
                alt="Commercial HVAC System"
                width={700}
                loading="lazy"
                height={500}
                className="w-full h-auto rounded-xl shadow-xl border-2 border-cyan-100"
                
              />

            </div>


            <div className=" w-full md:w-6/12">

              <h1 className=" text-lg md:text-2xl text-center md:text-left font-bold text-cyan-800 mb-6 leading-tight">
               How to Prevent Overheating in Electrical Cabinets : A Guide to Industrial Thermal Management

              </h1>

              <p className=" w-full md:w-10/12 text-sm text-gray-700 mb-6 text-justify md:text-left ">
             Protect your critical electronics from heat-related damage. This guide explores the causes of overheating and provides solutions, from simple fans to advanced panel air conditioners, to ensure your equipment runs reliably.

              </p>

             

            </div>

          </section>

          {/* Key Takeaways */}



          <section className="mb-16 bg-white p-3 md:p-8 rounded-xl shadow-md border border-cyan-100">
            <p className=" md:text-2xl   font-bold text-cyan-800 mb-6 pb-2 border-b-2 border-cyan-200">
              <span className="bg-cyan-600 text-white px-2 py-1 rounded-md">
            
              The Causes of Overheating

              </span>
            </p>
            <p className=' text-sm pb-4 text-justify'>Before you can solve the problem, you must understand its source. Overheating in electrical cabinets is typically caused by one or a combination of the following factors :
</p>
            <ul className="space-y-4">
              {KeyTakeaways.map((item, index) => (
                <li key={index} className="flex items-start ">
                  <span className="flex-shrink-0 bg-cyan-100 text-cyan-800 rounded-full p-2 mr-3">

                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>

                  </span>

                  <span className="text-gray-700  md:font-medium">
                 <strong className=' font-bold text-cyan-600'> {item.title} : </strong> {item.description}
                  </span>

                </li>
              ))}
            </ul>
          </section>

          {/* Main Content */}
          <div className="space-y-16">
            {/* Licensing Section */}
          
            {/* Experience Section */}
            <section className="bg-white md:p-8 p-3 rounded-xl shadow-md">
             

              <div className="mt-8">
                <h3 className="md:text-2xl font-semibold text-cyan-700 mb-4 text-center md:text-left">
               Adhunik Powertech : A Globally Trusted Solution

                </h3>
                <p className="text-gray-600 mb-4 text-sm text-justify md:text-left">
              When selecting a panel air conditioner, it's crucial to choose a partner with a proven track record. Adhunik Powertech is a top Indian manufacturer and an authorized government supplier, a testament to our commitment to quality and compliance. We have over 19 years of expertise and have successfully exported our robust, energy-efficient panel ACs to various countries, including the United States, United Arab Emirates, Saudi Arabia, Bangladesh, and Indonesia.
 </p>

 <p className="text-gray-600 mb-4 text-sm text-justify md:text-left">
    Our dedication to quality is backed by key certifications, including ISO 9001:2015, CE Marking, and ZED Bronze Certification, and we are a registered supplier on the GeM platform. We proudly serve a wide range of clients, such as Uflex Limited, Steel Authority of India Ltd. (SAIL), and Hero MotoCorp, ensuring reliable cooling for critical industrial operations worldwide.

 </p>

                <div className="bg-white border border-cyan-200 rounded-lg p-6 shadow-sm">
                  <h4 className="text-lg font-semibold  text-cyan-700 mb-3">
                 Critical Factors for Selection
                  </h4>
                  <p className=' pb-4 text-sm text-gray-500'>Once you've decided on the cooling technology, you must select the right size and type.
</p>
                  <ul className="space-y-3">

                    {ClientReferences.map((item, index) => (
                      <li key={index} className="flex items-start">
                        <span className="text-cyan-600 mr-2">•</span>
                        <span className="text-gray-700 text-sm">
                        {item.description}
                        </span>
                      </li>
                    ))}

                  </ul>
                </div>

                

              </div>
            </section>



            



            <section className="bg-white p-3 md:p-8 rounded-xl shadow-md border border-cyan-100 mb-16">
           

    
              <div className="mb-12">
                <h3 className="md:text-2xl text-center md:text-left font-semibold text-cyan-700 mb-4">
             The Solution - Choosing the Right Thermal Management System
  </h3>
                <p className="text-gray-700 mb-6  text-sm text-justify md:text-left">
                The solution isn't a one-size-fits-all approach. The best method depends on your specific heat load and the surrounding environment. Here are the most common solutions, from simple to advanced :

                </p>
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {energySystems.map((system, index) => (

                    <div key={index} className="bg-white flex flex-col   justify-start  md:items-start items-start  md:text-left text-center p-5 rounded-lg border border-cyan-100 hover:border-cyan-300 transition-all shadow-sm hover:shadow-md">

                      <div className="bg-cyan-100 w-12 h-12 rounded-full flex  items-center justify-center mb-4">
                        <svg className="w-6 h-6 text-cyan-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d={system.icon} />
                        </svg>
                      </div>

                      <div className="font-bold text-cyan-800 text-lg mb-2">{system.title}
                      </div>

                      <div className="text-gray-500 text-sm text-justify flex flex-col gap-2  ">{system.desc}</div>

                    </div>


                  ))}
                </div>

                
              </div>

             
            </section>



 



          


            <div className="px-6 lg:px-24 py-12 bg-white rounded-3xl shadow-2xl space-y-16">
         
 

              <div className="space-y-6 pt-10 border-t border-cyan-200">
                <h2 className=" md:text-2xl text-center md:text-left   font-bold text-cyan-700"> Conclusion : Proactive Cooling for Peace of Mind
</h2>
                <p className="text-gray-700 text-sm text-justify   leading-relaxed">
               Investing in the right thermal management system for your electrical cabinets is a proactive step that protects your equipment, reduces maintenance costs, and prevents unscheduled downtime. By understanding the causes of overheating and choosing a solution tailored to your specific needs, you ensure your industrial operations run smoothly, reliably, and efficiently for years to come.

                </p>
            
              </div>
            </div>



            {/* CTA Section */}
            <section className="bg-gradient-to-r from-cyan-600 to-cyan-800 rounded-xl p-8 text-white shadow-lg">
              <div className="text-center max-w-3xl mx-auto">
                <h2 className="  text-xl md:text-3xl font-bold mb-4">Get Expert Advice for Your Cooling Needs</h2>
                <p className="text-cyan-100 mb-8 text-sm md:text-lg">
            Ready to find the perfect cooling solution for your electrical cabinet? Contact our team of experts to discuss your specific needs and get a free, no-obligation consultation.
  </p>
                <div className="flex flex-col sm:flex-row justify-center gap-4">
                  <a
                    href="tel:8287885885"
                    className="bg-white text-sm md:text-md font-bold text-cyan-800 hover:bg-cyan-100  py-3 px-6 rounded-lg transition duration-300 flex items-center justify-center"
                  >
                    <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                    </svg>
                    Contact  Expert
                  </a>
                  <Link
                    href="/support-form"
                    className="bg-cyan-900 text-sm md:text-md hover:bg-cyan-700 text-white font-bold py-3 px-6 rounded-lg transition duration-300 flex items-center justify-center border border-cyan-700"
                  >
                    <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                    Enquiry Now
                  </Link>
                </div>
              </div>
            </section>

 



          </div>
        </div>
      </div>
    </>
  )
}
